=== lkrsnik/Grading/Java/Oddaja3/ocenjevanje/build/web/studenti.xsd
<?xml version = "1.0"?>

<!-- Simple W3C XML Schema document -->
<schema xmlns = "http://www.w3.org/2001/XMLSchema"    
   xmlns:deitel = "http://www.deitel.com/studenti"    
   targetNamespace = "http://www.deitel.com/studenti">

   <element name = "studenti" type = "deitel:StudentiType"/>

   <complexType name = "StudentiType">
      <sequence>
         <element name = "student" type = "deitel:StudentType"
            minOccurs = "1" maxOccurs = "unbounded"/>         
      </sequence>
   </complexType>

   <complexType name = "StudentType">
      <all>
         <element name = "ime" type = "string"/>
		 <element name = "priimek" type = "string"/>
		 <element name = "projekt" type = "string" minOccurs="0" maxOccurs="1"/>
      </all>
	  <attribute name="vpisna" type="string" use="required"/>
   </complexType>
</schema>

=== lkrsnik/Grading/Java/Oddaja3/ocenjevanje/web/studenti.xml
<?xml version="1.0"?>
<deitel:studenti xmlns:deitel="http://www.deitel.com/studenti" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.deitel.com/studenti studenti.xsd">
	<student vpisna="63110898">
		<ime>Janez</ime>
		<priimek>Novak</priimek>
		<projekt>projekt1</projekt>
	</student>
	<student vpisna="63110123">
		<ime>Micka</ime>
		<priimek>Pre≈°eren</priimek>
		<projekt>projekt3</projekt>
	</student>
	<student vpisna="63110007">
		<ime>James</ime>
		<priimek>Bond</priimek>
		<projekt>projekt7</projekt>
	</student>
</deitel:studenti>
